"""SA-8 trending destinations agent.

Single, cheap LLM call that returns 10 India + 10 international destinations
for Indian travellers, with a one-line blurb each. Driven by a season key
(`{season}-{year}`) so the refresh cadence is ~4 calls per year. The call
runs against Cerebras Qwen by default (see `Settings.LLM_TRENDING_*`).

Not a LangGraph node — this isn't part of the research pipeline. It's a
plain `async def` invoked by `POST /agent/trending-refresh`.
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from typing import Literal

from app.llm.factory import get_structured_llm
from app.schemas import TrendingPayload

logger = logging.getLogger(__name__)

Season = Literal["summer", "monsoon", "post-monsoon", "winter"]


def current_season(now: datetime | None = None) -> Season:
    """India-aware season. Mirror of nomad-api/src/services/season.service.ts.

    Months use UTC to match the Node helper (which calls `getUTCMonth`),
    so a refresh fired by Node and one fired by curl land on the same key.
    """
    now = now or datetime.now(timezone.utc)
    m = now.month  # 1 = Jan
    if 3 <= m <= 5:
        return "summer"
    if 6 <= m <= 9:
        return "monsoon"
    if 10 <= m <= 11:
        return "post-monsoon"
    return "winter"


def current_season_key(now: datetime | None = None) -> str:
    now = now or datetime.now(timezone.utc)
    return f"{current_season(now)}-{now.year}"


_PROMPT_TEMPLATE = """\
You are a travel-trend analyst for Indian travellers.

Generate exactly 10 trending destinations within India and exactly 10
trending international destinations for travellers based in India, for
{season} {year}.

Rules:
- Reflect realistic seasonal preferences for Indian travellers:
  * winter favours warmer or snowy destinations depending on intent
  * summer favours hill stations, Europe, and cool-climate spots
  * monsoon favours offbeat / lush / non-coastal places, avoids most beaches
  * post-monsoon is peak travel — broad mix
- Every entry must be a SPECIFIC place — a city, region, or landmark — NEVER a
  whole country. "country" must be different from "name" (e.g. name "Bali" /
  country "Indonesia"; name "Kyoto" / country "Japan").
- India list: only specific places inside India (cities / regions / hill
  stations). For these entries "country" MUST be the Indian state or union
  territory the place is in — NEVER the string "India"
  (e.g. name "Manali" / country "Himachal Pradesh"; name "Jaipur" /
  country "Rajasthan"; name "Goa" / country "Goa";
  name "Rishikesh" / country "Uttarakhand").
- International list: specific places (cities / regions / islands) outside
  India that are realistic for an Indian passport holder — favour
  visa-on-arrival, e-visa, or easy-visa countries.
- Each blurb: <= 15 words, evocative, no marketing fluff, no exclamation marks.
- duration: a short range like "5-7 days" or "3-4 days".
- vibe_tags: 1 to 3 short single-word lowercase tags (e.g. "beach",
  "heritage", "mountains", "food", "nightlife", "adventure", "spiritual",
  "luxury", "offbeat", "family", "romance", "wellness", "wildlife").
- Do not repeat a destination across the two lists.

Return a single JSON object with exactly this shape:
{{
  "season": "{season}",
  "year": {year},
  "india": [ 10 destination objects ],
  "international": [ 10 destination objects ]
}}

Each destination object has exactly these fields:
  "name":      string — a specific place (city/region/landmark), never a country
  "country":   string — the nation that place is in, different from "name"
  "duration":  string — short range like "5-7 days"
  "blurb":     string — <= 15 words, no exclamation marks
  "vibe_tags": array of 1 to 3 short lowercase single-word tags

Output ONLY the JSON object — no prose, no markdown code fences.
"""


async def generate_trending(
    season: Season | None = None,
    year: int | None = None,
) -> TrendingPayload:
    """Run the LLM call and return a validated TrendingPayload."""
    now = datetime.now(timezone.utc)
    season = season or current_season(now)
    year = year or now.year

    prompt = _PROMPT_TEMPLATE.format(season=season, year=year)
    logger.info("[trending] generating payload for season=%s year=%s", season, year)

    # json_mode (response_format={"type":"json_object"}) instead of the default
    # json_schema mode: Cerebras' structured-output validator rejects the
    # minItems/maxItems keywords generated by TrendingPayload's list length
    # constraints. json_mode sends no schema; the result is still validated
    # against TrendingPayload client-side, so the wire contract is unchanged.
    llm = get_structured_llm("trending", TrendingPayload, method="json_mode")
    payload: TrendingPayload = await llm.ainvoke(prompt)

    # The schema enforces lengths/types; nothing extra to validate here.
    return payload
